### PR TITLE
Introduce our brand new website!

### PR DESCRIPTION
**Pull request by allejo**
A little self-promotion here with my theme of choice, [jekyll-docs-theme](https://github.com/allejo/jekyll-docs-theme) :wink:

But here's the rough initial draft of what the website will look like.

## Todo

- [x] Make sidebar scrollable with long groups (e.g. functions is super long)
- [x] Syntax highlight all of the code blocks in the examples

### CODE REVIEW

**Comment by MonsieurV** [comment]
:tada: 

Can we have a composer `scripts` entry to build and test the site locally? :smiley:

**Comment by allejo** [comment]
> Can we have a composer `scripts` entry to build and test the site locally? 😃

Added `composer site` in 3171cb6a43cb5bf196bbe4cfb6b54f87f70f10aa :smile:

**Comment by maciejczyzewski** [comment]
image
very sweet!

**Comment by MonsieurV** [comment]
That's neat! :raised_hands:

**Comment by allejo** [comment]
@MonsieurV I've enabled the offset to be configurable via front matter and set to 200 pixels. Would you like to play around with that setting?

**Comment by MonsieurV** [comment]
> @MonsieurV I've enabled the offset to be configurable via front matter and set to 200 pixels. Would you like to play around with that setting?

Tested, that's perfect for me!
@allejo Great Jekyll theme :)

**Pull request merged**
